## Basic Configuration

baseurl = "/" 
builddrafts = false
canonifyurls = false
languageCode = "en-US"

contentdir = "content"
layoutdir = "layouts"
publishdir = "public"

author = "Kieran Mason-Somers"
title = "KMSOMERS"

theme = "hugo-goa"

## Hugo Built-in Features
disqusShortname = "https-shenoybr-github-io-hugo-goa-demo" # Comment out to disable Disqus.
googleAnalytics = "XYZ"
enableRobotsTXT = true

## Site Settings
[params]
author = "Kieran Mason-Somers"
intro = "Junior Mobile Developer - Android / Web"
description = "Mobile team at Hillary Blinds - Previously studied Computer Science at the University of Lincoln."
authorimage = "test.jpg"
dateformat = "Jan 2, 2006"

## Site Meta Settings
[params.meta]
description = "Simple minimalist theme"
keywords = "minimalist,blog,goa,hugo,developer,android,react,go"

## Social Accounts
[params.social]
github = "kmsomers"
instagram = "<username>"
linkedin = "kieran-mason-somers-9709a9126"
twitter = "kmsomersx"
facebook = "kieran.somers.7"
email = "kieran.somers5@gmail.com"

## Extras
[params.extra]
copyright = "© 2018. Kieran Mason-Somers. [Some Rights Reserved](http://creativecommons.org/licenses/by/3.0/)." 
poweredby = true
highlightjs = true

## Main Menu
[[menu.main]]
    name = "About"
    identifier = "About"
    weight = 200
    url = "/about/"
[[menu.main]]
    name = "Blog"
    weight = 100
    identifier = "Blog"
    url = "/post/"

